name: Update manifests

on:
  schedule:
    - cron: 0 7 * * *
  workflow_dispatch:

jobs:
  autopr:
    name: Update manifests
    runs-on: windows-latest
    steps:
      - name: Checkout bucket
        uses: actions/checkout@v2
        with:
          path: bucket

      - name: Checkout scoop
        uses: actions/checkout@v2
        with:
          repository: lukesampson/scoop
          path: scoop\apps\scoop\current

      - name: Setup scoop
        run: |
          . $env:SCOOP\apps\scoop\current\lib\core.ps1
          shim "$env:SCOOP\apps\scoop\current\bin\scoop.ps1" $false
          ensure "$env:SCOOP\buckets\main"
        env:
          SCOOP: ${{ github.workspace }}\scoop

      - name: Run auto-pr.ps1
        run: |
          $env:path += ";$env:SCOOP\shims"
          $env:GIT_REDIRECT_STDERR = '2>&1' # https://github.com/dahlbyk/posh-git/issues/109
          $env:GIT_AUTHOR_NAME = 'GitHub Action'
          $env:EMAIL = 'noreply@github.com'
          .\bin\auto-pr.ps1 -Push
        working-directory: ${{ github.workspace }}\bucket
        env:
          SCOOP: ${{ github.workspace }}\scoop
