name: Update manifests

on:
  schedule:
    - cron: 0 7 * * *

jobs:
  autopr:
    name: Update manifest
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          path: bucket

      - name: Setup scoop
        run: Invoke-Expression (New-Object System.Net.WebClient).DownloadString('https://raw.githubusercontent.com/lukesampson/scoop/master/bin/install.ps1')

      - name: Setup Hub
        uses: Geertvdc/setup-hub@v1.0.0

      - name: Run auto-pr.ps1
        run: |
          $env:path += ";$env:userprofile\scoop\shims"
          $env:GIT_REDIRECT_STDERR = '2>&1' # https://github.com/dahlbyk/posh-git/issues/109
          $env:GIT_AUTHOR_NAME = 'GitHub Action'
          $env:EMAIL = 'noreply@github.com'
          .\bin\auto-pr.ps1 -Push
        working-directory: ${{ github.workspace }}\bucket
